# Generated by Django 5.2.4 on 2025-08-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager (Administrateur)'), ('COMMERCIAL_SHOWROOM', 'Commercial Showroom (Ventes)'), ('COMMERCIAL_TERRAIN', 'Commercial Terrain (Commandes/Clients)'), ('TECHNICIEN', 'Technicien (Stock/SAV)')], default='TECHNICIEN', max_length=25),
        ),
    ]
