# Generated by Django 5.2.4 on 2025-08-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telephone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
