# Generated by Django 5.2.4 on 2025-09-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Manager (Administrateur)"),
                    ("COMMERCIAL_SHOWROOM", "Commercial 1 (Clients/Ventes/Commandes)"),
                    ("COMMERCIAL_TERRAIN", "Commercial 2 (Clients/Devis/Prospects)"),
                    ("TECHNICIEN", "Technicien (Stock/SAV)"),
                ],
                default="TECHNICIEN",
                max_length=25,
            ),
        ),
    ]
