# Generated by Django 5.2.4 on 2025-08-13 16:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=20)),
                ("adresse", models.TextField()),
                ("ville", models.CharField(max_length=50)),
                ("code_postal", models.CharField(max_length=10)),
                ("pays", models.CharField(default="France", max_length=50)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=20)),
                ("adresse", models.TextField()),
                ("ville", models.CharField(max_length=50)),
                ("code_postal", models.CharField(max_length=10)),
                ("pays", models.CharField(default="France", max_length=50)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
            },
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_commande", models.CharField(max_length=50, unique=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("CONFIRMEE", "Confirmée"),
                            ("EXPEDIEE", "Expédiée"),
                            ("LIVREE", "Livrée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                ("date_livraison_prevue", models.DateField(blank=True, null=True)),
                ("adresse_livraison", models.TextField()),
                ("notes", models.TextField(blank=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.client",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "ordering": ["-date_commande"],
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("code_barre", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "quantite_stock",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "seuil_alerte",
                    models.IntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="produits/"),
                ),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.categorie",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("ENTREE", "Entrée"),
                            ("SORTIE", "Sortie"),
                            ("AJUSTEMENT", "Ajustement"),
                            ("RETOUR", "Retour"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("quantite_avant", models.IntegerField()),
                ("quantite_apres", models.IntegerField()),
                ("motif", models.CharField(max_length=200)),
                ("date_mouvement", models.DateTimeField(auto_now_add=True)),
                ("numero_lot", models.CharField(blank=True, max_length=50)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de Stock",
                "verbose_name_plural": "Mouvements de Stock",
                "ordering": ["-date_mouvement"],
            },
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.commande",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de Commande",
                "verbose_name_plural": "Lignes de Commande",
            },
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_vente", models.CharField(max_length=50, unique=True)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("ESPECES", "Espèces"),
                            ("CARTE", "Carte bancaire"),
                            ("CHEQUE", "Chèque"),
                            ("VIREMENT", "Virement"),
                            ("CREDIT", "Crédit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_vente", models.DateTimeField(auto_now_add=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.client",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vente",
                "verbose_name_plural": "Ventes",
                "ordering": ["-date_vente"],
            },
        ),
        migrations.CreateModel(
            name="LigneVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.produit",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de Vente",
                "verbose_name_plural": "Lignes de Vente",
            },
        ),
    ]
