# Generated by Django 5.2.4 on 2025-08-25 15:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppareilVendu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_serie", models.CharField(max_length=100, unique=True)),
                ("date_installation", models.DateField()),
                ("lieu_installation", models.CharField(max_length=200)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("INSTALLE", "Installé"),
                            ("EN_SERVICE", "En service"),
                            ("MAINTENANCE", "En maintenance"),
                            ("PANNE", "En panne"),
                            ("HORS_SERVICE", "Hors service"),
                        ],
                        default="INSTALLE",
                        max_length=20,
                    ),
                ),
                ("prochaine_maintenance_preventive", models.DateField()),
                ("derniere_maintenance", models.DateField(blank=True, null=True)),
                ("intervalle_maintenance_jours", models.IntegerField(default=365)),
                ("notes_installation", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.client",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.produit",
                    ),
                ),
                (
                    "technicien_responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appareils_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appareils",
                        to="inventory.vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appareil Vendu",
                "verbose_name_plural": "Appareils Vendus",
                "ordering": ["prochaine_maintenance_preventive"],
            },
        ),
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_devis", models.CharField(max_length=50, unique=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("ENVOYE", "Envoyé"),
                            ("ACCEPTE", "Accepté"),
                            ("REFUSE", "Refusé"),
                            ("EXPIRE", "Expiré"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_validite", models.DateField()),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("conditions_particulieres", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devis",
                        to="inventory.client",
                    ),
                ),
                (
                    "commercial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devis_commerciaux",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="InterventionSAV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_intervention", models.CharField(max_length=50, unique=True)),
                (
                    "type_intervention",
                    models.CharField(
                        choices=[
                            ("PREVENTIVE", "Maintenance préventive"),
                            ("CORRECTIVE", "Maintenance corrective"),
                            ("INSTALLATION", "Installation"),
                            ("FORMATION", "Formation"),
                            ("DIAGNOSTIC", "Diagnostic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_prevue", models.DateTimeField()),
                ("date_realisee", models.DateTimeField(blank=True, null=True)),
                ("duree_prevue", models.IntegerField(help_text="Durée en minutes")),
                (
                    "duree_reelle",
                    models.IntegerField(
                        blank=True, help_text="Durée en minutes", null=True
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIEE", "Planifiée"),
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminée"),
                            ("REPORTEE", "Reportée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="PLANIFIEE",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("travaux_realises", models.TextField(blank=True)),
                ("pieces_changees", models.TextField(blank=True)),
                ("observations", models.TextField(blank=True)),
                (
                    "note_satisfaction",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("commentaire_client", models.TextField(blank=True)),
                (
                    "appareil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="inventory.appareilvendu",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.client",
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions_technicien",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention SAV",
                "verbose_name_plural": "Interventions SAV",
                "ordering": ["date_prevue"],
            },
        ),
        migrations.CreateModel(
            name="LigneDevis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.devis",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de Devis",
                "verbose_name_plural": "Lignes de Devis",
            },
        ),
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("entreprise", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                ("adresse", models.TextField(blank=True)),
                ("ville", models.CharField(blank=True, max_length=50)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NOUVEAU", "Nouveau"),
                            ("CONTACTE", "Contacté"),
                            ("INTERESSE", "Intéressé"),
                            ("QUALIFIE", "Qualifié"),
                            ("PROPOSE", "Proposition envoyée"),
                            ("NEGOCIE", "En négociation"),
                            ("CONVERTI", "Converti en client"),
                            ("PERDU", "Perdu"),
                        ],
                        default="NOUVEAU",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_derniere_interaction", models.DateTimeField(auto_now=True)),
                (
                    "client_converti",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.client",
                    ),
                ),
                (
                    "commercial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prospects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prospect",
                "verbose_name_plural": "Prospects",
                "ordering": ["-date_derniere_interaction"],
            },
        ),
        migrations.CreateModel(
            name="NoteObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_note",
                    models.CharField(
                        choices=[
                            ("CLIENT", "Note Client"),
                            ("PROSPECT", "Note Prospect"),
                            ("INTERACTION", "Interaction"),
                            ("RELANCE", "Relance"),
                            ("REUNION", "Réunion"),
                            ("APPEL", "Appel téléphonique"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_rappel", models.DateTimeField(blank=True, null=True)),
                ("terminee", models.BooleanField(default=False)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="inventory.client",
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="inventory.prospect",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note d'Observation",
                "verbose_name_plural": "Notes d'Observation",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="TransfertStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_transfert", models.CharField(max_length=50, unique=True)),
                (
                    "quantite",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("origine", models.CharField(default="Dépôt", max_length=100)),
                ("destination", models.CharField(default="Showroom", max_length=100)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_expedition", models.DateTimeField(blank=True, null=True)),
                ("date_reception", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("EXPEDIE", "Expédié"),
                            ("RECU", "Reçu"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferts_demandes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferts_expedies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.produit",
                    ),
                ),
                (
                    "recepteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferts_recus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert de Stock",
                "verbose_name_plural": "Transferts de Stock",
                "ordering": ["-date_creation"],
            },
        ),
    ]
