# Generated by Django 5.2.4 on 2025-08-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_appareilvendu_devis_interventionsav_lignedevis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='entreprise',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
