# Generated by Django 5.2.4 on 2025-08-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_client_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionsav',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.client'),
        ),
    ]
