# Generated by Django 5.2.4 on 2025-11-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_update_devis_statut"),
    ]

    operations = []
