# Generated by Django 5.2.4 on 2025-11-17 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_add_prospect_new_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProspectionTelephonique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(max_length=200, verbose_name="Nom complet"),
                ),
                (
                    "numero_telephone",
                    models.CharField(max_length=20, verbose_name="Numéro téléphonique"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("RDV", "RDV"),
                            ("BV", "BV"),
                            ("CLIENT_ACQUIS", "Client acquis"),
                            ("A_RELANCER", "À relancer"),
                        ],
                        default="A_RELANCER",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_rdv",
                    models.DateField(blank=True, null=True, verbose_name="Date de RDV"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "type_appel",
                    models.CharField(
                        choices=[
                            ("SORTANT", "Appel sortant"),
                            ("ENTRANT", "Appel entrant"),
                        ],
                        max_length=20,
                        verbose_name="Type d'appel",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "source_prospect",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONTACT_EMAIL", "Contact email"),
                            ("APPEL_DIRECT", "Appel direct"),
                            ("SITE_WEB", "Site web"),
                            ("RESEAUX_SOCIAUX", "Réseaux sociaux"),
                            ("FLYER", "Flyer"),
                            ("VISIOCONFERENCE", "Visioconférence"),
                            ("BOUCHE_OREILLE", "Bouche à oreille"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Source de prospect",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "commercial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Commercial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prospection Téléphonique",
                "verbose_name_plural": "Prospections Téléphoniques",
                "ordering": ["-date_creation"],
            },
        ),
    ]
